"""initial schema

Revision ID: 4a780231d1ef
Revises: 
Create Date: 2026-06-18 14:23:11.744391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a780231d1ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('workflow_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('node_definition_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('node_definition_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_definition_id'], ['node_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_definition_id', 'version')
    )
    op.create_table('workflow_definition_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_definition_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_definition_id', 'version')
    )
    op.create_table('workflow_instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('workflow_definition_id', sa.String(), nullable=False),
    sa.Column('workflow_definition_version_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'CANCELLED', name='workflow_status'), nullable=False),
    sa.Column('current_revision', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workflow_definition_id'], ['workflow_definitions.id'], ),
    sa.ForeignKeyConstraint(['workflow_definition_version_id'], ['workflow_definition_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_instance_id', sa.String(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=True),
    sa.Column('current_hash', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_instance_id', 'sequence_number')
    )
    op.create_index('ix_workflow_events_instance_created', 'workflow_events', ['workflow_instance_id', 'created_at'], unique=False)
    op.create_table('workflow_node_instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_instance_id', sa.String(), nullable=False),
    sa.Column('workflow_node_id', sa.String(), nullable=False),
    sa.Column('node_definition_version_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'PENDING', 'RUNNING', 'COMPLETED', 'INVALIDATED', 'FAILED', name='node_status'), nullable=False),
    sa.Column('current_execution', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_definition_version_id'], ['node_definition_versions.id'], ),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_instance_id', 'workflow_node_id')
    )
    op.create_table('workflow_projections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_instance_id', sa.String(), nullable=False),
    sa.Column('current_state_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_instance_id')
    )
    op.create_table('workflow_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_instance_id', sa.String(), nullable=False),
    sa.Column('snapshot_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_instance_id')
    )
    op.create_table('workflow_node_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_instance_id', sa.String(), nullable=False),
    sa.Column('workflow_node_instance_id', sa.String(), nullable=False),
    sa.Column('execution_number', sa.Integer(), nullable=False),
    sa.Column('inputs_json', sa.JSON(), nullable=False),
    sa.Column('outputs_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='execution_status'), nullable=False),
    sa.Column('executed_by', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workflow_node_instance_id'], ['workflow_node_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_node_instance_id', 'execution_number')
    )
    op.create_table('workflow_node_projections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_instance_id', sa.String(), nullable=False),
    sa.Column('workflow_node_instance_id', sa.String(), nullable=False),
    sa.Column('current_values_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_node_instance_id'], ['workflow_node_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_node_instance_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_node_projections')
    op.drop_table('workflow_node_executions')
    op.drop_table('workflow_snapshots')
    op.drop_table('workflow_projections')
    op.drop_table('workflow_node_instances')
    op.drop_index('ix_workflow_events_instance_created', table_name='workflow_events')
    op.drop_table('workflow_events')
    op.drop_table('workflow_instances')
    op.drop_table('workflow_definition_versions')
    op.drop_table('node_definition_versions')
    op.drop_table('workflow_definitions')
    op.drop_table('node_definitions')
    # ### end Alembic commands ###
